[package]
name = "handy_io"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "A handy pattern and futures based asynchronous I/O library"
documentation = "https://docs.rs/handy_io"
homepage = "https://github.com/sile/handy_io"
repository = "https://github.com/sile/handy_io"
readme = "README.md"
keywords = ["futures", "async", "I/O", "pattern"]
license = "MIT"

[dependencies]
futures = "0.1"
byteorder = "0.5"
