[package]
name = "handy_async"
version = "0.2.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "A handy pattern and futures based asynchronous I/O library"
documentation = "https://docs.rs/handy_async"
homepage = "https://github.com/sile/handy_async"
repository = "https://github.com/sile/handy_async"
readme = "README.md"
keywords = ["futures", "async", "io", "pattern"]
license = "MIT"

[dependencies]
futures = "0.1"
byteorder = "0.5"
